### PR TITLE
Add a ScraperApp and GrounderApp

### PR DESCRIPTION
**Pull request by kwalcock**
This is just an example of what might be.

### CODE REVIEW

**Comment by kwalcock** [comment]
This is just a baby step that is hopefully in the right direction.  The GrounderApp would be turned into a REST app.  This does not use Annoy.  We have an inefficient, brute force KNN.  It may be too inefficient or it might not provide the desired distance measure, but I'd like to be convinced first.  It's easy to improve the efficiency by not sorting all the similarities in order to take a small number off the top.  This does not use a real parser or control stopwords, etc.  I don't know if that is desired.  It may depend on how people are searching.

**Comment by kwalcock** [comment]
I need to do something about the -SNAPSHOT dependency.  If need be I can do a release of Eidos.

**Comment by kwalcock** [comment]
Less discuss issues in #4.

**Comment by kwalcock** [comment]
I will try to make my example in GrounderApp look a little more like the Example example if it can.  It wasn't clear to me what that was exemplifying.

**Comment by BeckySharp** [comment]
for now, can we keep the other stuff around too?

**Comment by kwalcock** [comment]
Now that it's approved, I can change it.  The DatamartGrounder does not inherit from anything in Eidos because I share your concern.  It just borrows a couple of terms like the Grounding and ConceptEmbedding.  I'm leaning towards your use of Concept...

**Comment by kwalcock** [comment]
Continued at #4...

**Pull request merged**
