### PR TITLE
Divide the project into subprojects

### PR DESCRIPTION
**Pull request by kwalcock**
The main idea is to limit dependencies to eidos (and processors) to a portion that is unrelated to the webapp and other parts that need to start quickly.  Details follow...

### CODE REVIEW

**Comment by kwalcock** [comment]
Please ignore the individual commits that aren't very meaningful.  It's the final structure that is important.  Eidos and processors and Word2Vec are only used in the `indexer` subproject which needs to access ontologies, glove, etc.  The `scraper` subproject is special because it needs to know about REST requests, eventually elastic search, and special things like that.  `core` is dependent on lucene and other indexers and mostly serves as library support and storage for simple examples.  One example, ExampleApp, is the outline of what the webapp should be doing, but from the command line.  Even in sbt, the program starts in a small number of seconds.  The same goes for the webapp.

**Comment by kwalcock** [comment]
@zhengzhongliang has code in branches that I couldn't refactor.  It has heavyweight dependencies, so the files could be added to `indexer`.  However, a new `evaluator` subproject might be handy in none of that code requires any indexing.

**Comment by kwalcock** [comment]
Sometime soon we can talk about the particulars of what the REST API should do.

**Comment by zhengzhongliang** [comment]
> @zhengzhongliang has code in branches that I couldn't refactor. It has heavyweight dependencies, so the files could be added to `indexer`. However, a new `evaluator` subproject might be handy in none of that code requires any indexing.

@kwalcock Hi Keith, can we have a short meeting on Friday? Probably at 11:00 am or any time in the afternoon. Thanks!

**Comment by BeckySharp** [comment]
> @zhengzhongliang has code in branches that I couldn't refactor. It has heavyweight dependencies, so the files could be added to `indexer`. However, a new `evaluator` subproject might be handy in none of that code requires any indexing.

I like the idea of an `evaluator` subproject a lot.
Also, thanks for doing this!  I guess that the idea is that by putting this into subprojects we don't have to screw around in Eidos?  If so, that's a good idea and +1!

**Comment by BeckySharp** [comment]
@kwalcock I guess I should wait until this is merged to go through and prune my code, right?

**Comment by kwalcock** [comment]
@BeckySharp, I haven't given up on it yet.  I'd wait at least until the REST service is deployed.  It may be that it's my code that needs to be pruned.  It seems like the webapp and the evaluator (and other things) have significantly different goals and that different subprojects would be appropriate.

**Comment by kwalcock** [comment]
> > @zhengzhongliang has code in branches that I couldn't refactor. It has heavyweight dependencies, so the files could be added to `indexer`. However, a new `evaluator` subproject might be handy in none of that code requires any indexing.
> 
> I like the idea of an `evaluator` subproject a lot.
> Also, thanks for doing this! I guess that the idea is that by putting this into subprojects we don't have to screw around in Eidos? If so, that's a good idea and +1!

@zhengzhongliang, I meant "handy *if* none of that code requires any indexing" and I'll answer your email shortly.

**Pull request merged**
