### PR TITLE
Start the compositional grounding

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@maxaalexeeva, @alicekwak, @BeckySharp

This includes an example, particularly in CompositionalOntologyMapperApp, of how the compositional ontology *could* be handled.  It uses a brute force, impractical search through all combinations of values in the four "dimensions" of a compositional grounding.  We have 203 concepts, 91 processes, and 19 properties that can be attached to both the former.  This makes for 6.5 million combinations.  Right now in the datamarts we have around 12,000 variables.  Searching through those 6.5 million for a single datamart variable takes about 10 seconds.  Repeating 12,000 times requires around 33 hours.  That's probably going to require some smartness to replace the bruteness, even if someone finds a way to pick the very best result, which is still to be done.

The two methods datamartToOntologyMapping and ontologyToDatamartMapping show how one might naively perform the mapping.  They have been commented some, but it will be difficult to understand.  This is partly because of running everything through a KNN indexer.  That probably shouldn't be done in the experiment package, where using w2v (aka concept embeddings) would be the thing to use.  The two scorers, a DatamartScorer and OntologyScorer at the very least need additional thought and they might not even have the necessary arguments.  After thought, they probably need optimization to match expected results.

**Comment by BeckySharp** [comment]
awesome!!!! thanks!!!
re: speeds, did you end up indexing the possible combinations of the
compositional ontology things?

**Comment by kwalcock** [comment]
No, each dimension is indexed separately right now as if they were separate flat ontologies.  6.5 million vectors of 300 floats * 4 bytes / float * 4 dimensions > 31 GB estimated for an index.  It might work.  If it wasn't necessary to double up the properties or if the concept & property and process & property were in two separate indexes, it would seem more feasible.  I probably don't know enough about how a compositional grounding is formed to appreciate all the possibilities.

**Comment by kwalcock** [comment]
What I'm not yet doing is attempting to compositionally ground the 12,000 datamart variables through linguistic means.  That would account for datamartToCompositionalOntology.  The ontology to datamart would still seem difficult.

**Comment by kwalcock** [comment]
I think it would help the other way around.  The ontology vectors would be generated on the fly and would be matched up with the 4 x 300 length vectors coming from the datamart.  On the other hand, the grounding for a datamart item isn't a single grounding, but a list of K, so it's still not completely obvious.  When's the next meeting about this?

**Comment by BeckySharp** [comment]
great question -- let's schedule one in the next couple of days, are you
free today (Monday) at 3? else Tues at 1?

**Comment by alicekwak** [comment]
> great question -- let's schedule one in the next couple of days, are you free today (Monday) at 3? else Tues at 1?
> […](#)

@BeckySharp Hi Becky! @maxaalexeeva and I were wondering if you want us to attend the meeting that you're scheduling now. Are we supposed to the part of that meeting?

**Pull request merged**
