### PR TITLE
Webapp the OntologyMapper

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I need to go back over this at least once more, either before or after a merge.

**Comment by kwalcock** [comment]
I took out the secret to the bulk queries.  However, it looks like so many resources may be required that we only allow privileged users to execute the commands.  Right now they take longer to execute than a web browser, for instance, will generally allow.

The bulk query can be ready quite soon, but its availability is slowed by the wait for the searcher object which needs to support other queries.  I could change that if necessary by putting it in a separate component.  That is complicated by the sharing of the datamart query component.

**Comment by kwalcock** [comment]
The full bulk query, mapping everything to everything and in both directions, occupies around 650MB when output as text.  It will be even larger as json.  If this is the data they would prefer to have, we can call it an index and just return the whole file.  It *seems* like the mapping is fairly quick.  Perhaps it's the conversion to json that slows things down.  I'll be checking.

**Comment by kwalcock** [comment]
We can refer Uncharted to webapp.yml.

**Comment by BeckySharp** [comment]
@kwalcock thank you so much

**Pull request merged**
